[scw-cranky-chebyshev][[28617,1],7][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],7][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],1][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],1][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],7][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],7][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],1][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],1][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],7][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],7][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],1][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],1][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],1][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],7][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],0][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],0][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],0][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],0][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],0][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],0][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],4][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],4][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],4][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],4][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],4][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],4][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],4][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],2][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],2][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],2][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],2][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],2][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],2][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],2][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],6][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],6][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],6][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],6][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],6][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],6][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],6][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],5][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],5][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],5][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],3][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],5][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],3][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],5][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],3][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],5][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],3][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],5][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],3][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],3][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],3][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
[scw-cranky-chebyshev][[28617,1],0][btl_tcp_proc.c:266:mca_btl_tcp_proc_create_interface_graph] Unable to find reachable pairing between local and remote interfaces
Using the latest cached version of the dataset since benstaf/nasdaq_2013_2023 couldn't be found on the Hugging Face Hub
Using the latest cached version of the dataset since benstaf/nasdaq_2013_2023 couldn't be found on the Hugging Face Hub
Traceback (most recent call last):
  File "/root/FinRL_LLM/train_cppo_llama_risk.py", line 39, in <module>
    dataset = load_dataset("benstaf/nasdaq_2013_2023", data_files="train_data_llama_risk_2013_2018.csv")
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/load.py", line 2129, in load_dataset
Traceback (most recent call last):
  File "/root/FinRL_LLM/train_cppo_llama_risk.py", line 39, in <module>
    dataset = load_dataset("benstaf/nasdaq_2013_2023", data_files="train_data_llama_risk_2013_2018.csv")
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/load.py", line 2129, in load_dataset
    builder_instance = load_dataset_builder(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/load.py", line 1886, in load_dataset_builder
    builder_instance = load_dataset_builder(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/load.py", line 1886, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 124, in __init__
    builder_instance: DatasetBuilder = builder_cls(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 124, in __init__
    config_name, version, hash = _find_hash_in_cache(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 64, in _find_hash_in_cache
    raise ValueError(
ValueError: Couldn't find cache for benstaf/nasdaq_2013_2023 for config 'default-1c81dc53bc1e07bb'
Available configs in the cache: ['default-2206ff7de26da7cf', 'default-3b6952753eecfb91', 'default-68abb861e47a2b16', 'default-9c8b8a4499b78f78', 'default-e47a85f06662a0f9']
    config_name, version, hash = _find_hash_in_cache(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 64, in _find_hash_in_cache
    raise ValueError(
ValueError: Couldn't find cache for benstaf/nasdaq_2013_2023 for config 'default-1c81dc53bc1e07bb'
Available configs in the cache: ['default-2206ff7de26da7cf', 'default-3b6952753eecfb91', 'default-68abb861e47a2b16', 'default-9c8b8a4499b78f78', 'default-e47a85f06662a0f9']
Using the latest cached version of the dataset since benstaf/nasdaq_2013_2023 couldn't be found on the Hugging Face Hub
Traceback (most recent call last):
  File "/root/FinRL_LLM/train_cppo_llama_risk.py", line 39, in <module>
    dataset = load_dataset("benstaf/nasdaq_2013_2023", data_files="train_data_llama_risk_2013_2018.csv")
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/load.py", line 2129, in load_dataset
    builder_instance = load_dataset_builder(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/load.py", line 1886, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 124, in __init__
    config_name, version, hash = _find_hash_in_cache(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 64, in _find_hash_in_cache
    raise ValueError(
ValueError: Couldn't find cache for benstaf/nasdaq_2013_2023 for config 'default-1c81dc53bc1e07bb'
Available configs in the cache: ['default-2206ff7de26da7cf', 'default-3b6952753eecfb91', 'default-68abb861e47a2b16', 'default-9c8b8a4499b78f78', 'default-e47a85f06662a0f9']
Using the latest cached version of the dataset since benstaf/nasdaq_2013_2023 couldn't be found on the Hugging Face Hub
Traceback (most recent call last):
  File "/root/FinRL_LLM/train_cppo_llama_risk.py", line 39, in <module>
    dataset = load_dataset("benstaf/nasdaq_2013_2023", data_files="train_data_llama_risk_2013_2018.csv")
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/load.py", line 2129, in load_dataset
    builder_instance = load_dataset_builder(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/load.py", line 1886, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 124, in __init__
    config_name, version, hash = _find_hash_in_cache(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 64, in _find_hash_in_cache
    raise ValueError(
ValueError: Couldn't find cache for benstaf/nasdaq_2013_2023 for config 'default-1c81dc53bc1e07bb'
Available configs in the cache: ['default-2206ff7de26da7cf', 'default-3b6952753eecfb91', 'default-68abb861e47a2b16', 'default-9c8b8a4499b78f78', 'default-e47a85f06662a0f9']
Using the latest cached version of the dataset since benstaf/nasdaq_2013_2023 couldn't be found on the Hugging Face Hub
Traceback (most recent call last):
  File "/root/FinRL_LLM/train_cppo_llama_risk.py", line 39, in <module>
    dataset = load_dataset("benstaf/nasdaq_2013_2023", data_files="train_data_llama_risk_2013_2018.csv")
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/load.py", line 2129, in load_dataset
    builder_instance = load_dataset_builder(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/load.py", line 1886, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 124, in __init__
    config_name, version, hash = _find_hash_in_cache(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 64, in _find_hash_in_cache
    raise ValueError(
ValueError: Couldn't find cache for benstaf/nasdaq_2013_2023 for config 'default-1c81dc53bc1e07bb'
Available configs in the cache: ['default-2206ff7de26da7cf', 'default-3b6952753eecfb91', 'default-68abb861e47a2b16', 'default-9c8b8a4499b78f78', 'default-e47a85f06662a0f9']
Using the latest cached version of the dataset since benstaf/nasdaq_2013_2023 couldn't be found on the Hugging Face Hub
Traceback (most recent call last):
  File "/root/FinRL_LLM/train_cppo_llama_risk.py", line 39, in <module>
    dataset = load_dataset("benstaf/nasdaq_2013_2023", data_files="train_data_llama_risk_2013_2018.csv")
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/load.py", line 2129, in load_dataset
    builder_instance = load_dataset_builder(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/load.py", line 1886, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 124, in __init__
    config_name, version, hash = _find_hash_in_cache(
  File "/root/miniconda3/envs/myenv/lib/python3.10/site-packages/datasets/packaged_modules/cache/cache.py", line 64, in _find_hash_in_cache
    raise ValueError(
ValueError: Couldn't find cache for benstaf/nasdaq_2013_2023 for config 'default-1c81dc53bc1e07bb'
Available configs in the cache: ['default-2206ff7de26da7cf', 'default-3b6952753eecfb91', 'default-68abb861e47a2b16', 'default-9c8b8a4499b78f78', 'default-e47a85f06662a0f9']
/root/FinRL_LLM/train_cppo_llama_risk.py:60: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['llm_sentiment'].fillna(0, inplace=True) #0 is outside scope of sentiment scores (min is 1)
/root/FinRL_LLM/train_cppo_llama_risk.py:62: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['llm_risk'].fillna(3, inplace=True) #neutral risk score is 3
Stock Dimension: 84, State Space: 1009
/root/FinRL_LLM/train_cppo_llama_risk.py:60: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['llm_sentiment'].fillna(0, inplace=True) #0 is outside scope of sentiment scores (min is 1)
/root/FinRL_LLM/train_cppo_llama_risk.py:62: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['llm_risk'].fillna(3, inplace=True) #neutral risk score is 3
Stock Dimension: 84, State Space: 1009
